esphome:
  name: infrared-module-1
  friendly_name: Infrared Module 1

esp8266:
  board: esp01_1m

logger:

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  fast_connect: True

  ap:
    ssid: "Infrared-Module-1"

captive_portal:

remote_receiver:
  id: ir_receiver
  pin:
    number: GPIO14
    inverted: True
    mode: INPUT_PULLUP
  dump: all
  on_nec:
    then:
      - homeassistant.event:
          event: esphome.nec_received
          data:
            address: !lambda "return x.address & 0xFF;"
            command: !lambda "return x.command & 0xFF;"

remote_transmitter:
  pin: GPIO4
  carrier_duty_percent: 50%

api:
  encryption:
    key: !secret api_encryption_key

  services:
    - service: transmit_nec
      variables:
        address: int
        command: int
      then:
        - remote_transmitter.transmit_nec:
            address: !lambda |-
              uint16 a = address & 0xFF;
              return (~a << 8) | a;
            command: !lambda |-
              uint16 c = command & 0xFF;
              return (~c << 8) | c;

climate:
  - platform: whynter
    name: "Whynter Arc-14S"
    supports_cool: true
    supports_heat: false
    receiver_id: ir_receiver
    use_fahrenheit: true

button:
  # LG codes not on remote from https://gitlab.com/-/snippets/1690600
  # LG style codes converted to NEC by reversing the 16 bits each for address and command
  - platform: template
    name: LG TV Power Toggle
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0xF708
  - platform: template
    name: LG TV Power Off
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0x3AC5
  - platform: template
    name: LG TV Power On
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0x3BC4
  - platform: template
    name: LG TV Input HDMI 1
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0x31CE
  - platform: template
    name: LG TV Input HDMI 2
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0x33CC
  - platform: template
    name: LG TV Input HDMI 3
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0x16E9
  - platform: template
    name: LG TV Input HDMI 4
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0x25DA

  # Controls this HDMI 2.1 4x1 switch: https://www.amazon.com/gp/product/B09STMC798?ie=UTF8&psc=1
  # Oddly the remote has a second set of 1-4 inputs so this probably also controls a 4x2 matrix
  - platform: template
    name: AVSTAR Switch Power Toggle
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x7F80
          command: 0xFC03
  - platform: template
    name: AVSTAR Switch Input 1
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x7F80
          command: 0xFE01
  - platform: template
    name: AVSTAR Switch Input 2
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x7F80
          command: 0xFB04
  - platform: template
    name: AVSTAR Switch Input 3
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x7F80
          command: 0xFD02
  - platform: template
    name: AVSTAR Switch Input 4
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x7F80
          command: 0xF20D
  - platform: template
    name: AVSTAR Switch Previous Input
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x7F80
          command: 0xE51A
  - platform: template
    name: AVSTAR Switch Next Input
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x7F80
          command: 0xF609

  # Controls this 4k60 5x1 switch: https://www.amazon.com/gp/product/B09Y14JSFH?ie=UTF8&th=1
  # This switch's remote does not have a power button.
  - platform: template
    name: UGREEN Switch Input 1
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x7F80
          command: 0xFA05
  - platform: template
    name: UGREEN Switch Input 2
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x7F80
          command: 0xF609
  - platform: template
    name: UGREEN Switch Input 3
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x7F80
          command: 0xF807
  - platform: template
    name: UGREEN Switch Input 4
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x7F80
          command: 0xE41B
  - platform: template
    name: UGREEN Switch Input 5
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x7F80
          command: 0xF708
  - platform: template
    name: UGREEN Switch Next Input
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x7F80
          command: 0xE01F

  # Controls this 4k60 5x1 switch: https://www.amazon.com/gp/product/B087CTR22G?ie=UTF8&psc=1
  # And many other identical switches under different brands
  - platform: template
    name: PONYBRO Switch Off
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xE01F
  - platform: template
    name: PONYBRO Switch On
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xA35C
  - platform: template
    name: PONYBRO Switch Input 1
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xE41B
  - platform: template
    name: PONYBRO Switch Input 2
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xE11E
  - platform: template
    name: PONYBRO Switch Input 3
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xF20D
  - platform: template
    name: PONYBRO Switch Input 4
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xED12
  - platform: template
    name: PONYBRO Switch Input 5
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xEF10
  - platform: template
    name: PONYBRO Switch Previous Input
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xF30C
  - platform: template
    name: PONYBRO Switch Next Input
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xFA05

  # Controls the RetroTINK 5x Pro, with IR Codes from https://consolemods.org/wiki/AV:RetroTINK-5X_Pro#Remote_Control
  # Most(?) of these had to be reversed like the LG codes so I think the wiki is wrong
  - platform: template
    name: RetroTINK 5x Pro Power
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x4CB3
          command: 0x23DC
  - platform: template
    name: RetroTINK 5x Pro Profile 1
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x4CB3
          command: 0x6D92
  - platform: template
    name: RetroTINK 5x Pro Profile 2
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x4CB3
          command: 0x6C93
  - platform: template
    name: RetroTINK 5x Pro Profile 3
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x4CB3
          command: 0x33CC
  - platform: template
    name: RetroTINK 5x Pro Profile 4
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x4CB3
          command: 0x718E
  - platform: template
    name: RetroTINK 5x Pro Profile 5
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x4CB3
          command: 0x708F
  - platform: template
    name: RetroTINK 5x Pro Profile 6
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x4CB3
          command: 0x37C8
  - platform: template
    name: RetroTINK 5x Pro Profile 7
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x4CB3
          command: 0x758A
  - platform: template
    name: RetroTINK 5x Pro Profile 8
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x4CB3
          command: 0x748B
  - platform: template
    name: RetroTINK 5x Pro Profile 9
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x4CB3
          command: 0x3BC4
  - platform: template
    name: RetroTINK 5x Pro Profile 10
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x4CB3
          command: 0x7887
